{
    'name': "School Management System",
    'summary': "Summery of School Management System",
    'author': 'Krish Prajapati',
    'category': 'School Management',
    'version': '19.0.1.0.0',
    'depends': ['base', 'contacts', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/sequence.xml',
        'views/announcement_view.xml',
        'views/student_view.xml',
        'views/admission_view.xml',
        'views/teacher_view.xml',
        'views/standard_view.xml',
        'views/subject_view.xml',
        'views/hobbies_view.xml',
        'views/exam_view.xml',
        'views/exam_lines_view.xml',
        'views/student_exam_view.xml',
        'views/student_exam_line_view.xml',
        'views/attendance_view.xml',
        'views/attendanceLine_view.xml',
        'views/fee_structure_view.xml',
        'views/student_fee_view.xml',
        'views/student_fees_payment_view.xml',
        'views/timetable_view.xml',
        'views/users_view.xml',
        'reports/student_fee_report.xml',
        'reports/student_exam_result_report.xml',
        'views/menu.xml',
    ],
    "application": True,
    "installable": True,
    "sequence": -2000
}
