{
    'name': "Property Sale and Rental Management System",
    'summary': "Sale and Rent",
    'author': 'Krish Prajapati',
    'category': 'Sale and Rental Management',
    'version': '19.0.1.0.0',
    'depends': ['base', 'contacts', 'base_vat', 'sale', 'account', 'stock', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_cron.xml',
        'reports/picking_report.xml',
        'views/property_view.xml',
        'views/property_offer_view.xml',
        'views/property_sale_deal_view.xml',
        'views/property_rent_deal_view.xml',
        'views/property_payment_records.xml',
        'views/property_rent_lines_view.xml',
        'views/reject_reasons_view.xml',
        'wizard/reject_reason_wizard_view.xml',
        'wizard/reject_reason_all_deal_line_wizard_view.xml',
        'wizard/res_config_setting_inherit_view.xml',
        'wizard/sale_order_confirm_wizard_view.xml',
        'views/owners_view.xml',
        'views/sale_order_info.xml',
        'views/sale_order_inherit_view.xml',
        'views/stock_picking_inherit_view.xml',
        'views/account_move_inherit_view.xml',
        'views/purchase_order_inherit_view.xml',
        'views/sequence.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'property_sale_and_rental_management_system/static/src/xml/other_button.xml',
        ]
    },
    "application": True,
    "installable": True,
    "sequence": -1000,
}
